Still broke with:
PendingRollbackError
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_sqlite3.IntegrityError) NOT NULL constraint failed: book.title
[SQL: INSERT INTO book (author) VALUES (?)]
[parameters: (None,)]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)

sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_sqlite3.IntegrityError) NOT NULL constraint failed: book.title
[SQL: INSERT INTO book (author) VALUES (?)]
[parameters: (None,)]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)